### ISSUE TITLE
Utilize $KITTY_LISTEN_ON if available

### ISSUE THREAD

**Issue by SevereOverfl0w** [knubie/vim-kitty-navigator#1]
This is set when the --listen-on flag is provided. In fact, you don't need a --to option at all if it is set!

**Comment by knubie** [comment]
Oh, cool; I didn't know about `$KITTY_LISTEN_ON`. Is that documented somewhere? I'll utilize it if I can learn more about how it works.

**Comment by sethwoodworth** [comment]
I only learned about the variable by looking through the kitty source for `os.environ['KITTY_LISTEN_ON']`

**Comment by strogonoff** [comment]
I believe that vim-kitty-navigator doesn’t need to specify an address to talk to Kitty through, actually. I’m using a version without it currently. (https://github.com/knubie/vim-kitty-navigator/pull/4)

**Comment by knubie** [comment]
Closed by #4
