### ISSUE TITLE
Strange behavior when title is hardcoded

### ISSUE THREAD

**Issue by fladson** [knubie/vim-kitty-navigator#10]
Hi @knubie, first, thank you so much for putting this together, I am trying to replace tmux with kitty tabs and windows and this is helping a lot on that, thank you.

I like to set tab titles manually so at first I thought that the code was not going to work without some customisation, but this is valid only for the first launched window, i.e. the mappings aren't working when inside nvim. The interesting finding is that If I open new windows or tabs, for some reason that I could not yet isolate, the mappings are working with no issues.

I have `--title=untitled` as launch option and for new tabs I also set the title manually so nvim is not overwriting the window title as far as I can see.

Any idea on why this is happening? I can help debugging if you are interested in solving this.

**Comment by knubie** [comment]
Hey @fladson thanks for opening an issue. I don't think this plugin has anything to do with kitty tabs. It just works with split windows. Renaming a tab shouldn't be an issue. My tabs are always renamed.

There might be something else that is happening that's causing it to not work in that first tab. Maybe try changing the current working directory on the first tab and see if that has any effect?

**Comment by fladson** [comment]
Hey @knubie, what I meant with the tabs is more related to windows titles, because the tab title, at the end, is just reflecting the window title, right? So I was not referring to navigation between tabs.

So you are saying that the window title does not affect the behavior of the tool?

I will try to collect more information and maybe record a video with the behavior.

**Comment by knubie** [comment]
Ok I think I understand, but maybe I'm still a little lost.

Let's say you have three split windows open and one of them has nvim loaded. Are you saying that the navigator keys work with the two non-nvim splits, but not within nvim?

The title of the window does matter, but only for the window containing neovim. The code assumes the title of the window containing nvim matches the regex `/n?vim/` (that is how it knows you're in neovim), but you can also configure a custom regex in in `kitty.conf` (details in the README.md).
