### ISSUE TITLE
Does not work with kitty 0.20.0+

### ISSUE THREAD

**Issue by aljets** [knubie/vim-kitty-navigator#20]
See kitty commit:
https://github.com/kovidgoyal/kitty/commit/774a6c8c8bb1fbafd83bdcd598d64d7f7f1e2983#diff-f6baac98965e7e357c7dc7efe071c82de011ec8a14bf1f9fac7b6410326a3f2f

Key constants are removed. Thus an exception is raised in `pass_keys.py` for `getattr(fdt, 'GLFW_FKEY_{}'.format(key.upper()))`

It may seem like it works initially because if you raise an exception in `pass_keys.py` you can hop around vim -- for a bit. But you can still see that `pass_keys.py` raises an exception and functionality stops.

EDIT to add: love what this program promises, and thanks for creating. As I get capacity it's possible I can dive into this further.

**Comment by knubie** [comment]
Thanks for the heads up @aljets!
We've seen a breaking change like this before recently with #19 so hopefully this one won't be to difficult to patch as well. I'm not a python programmer, so it's a bit out of my element but I will also take a look on my end. Appreciate a PR if you are able.
