### ISSUE TITLE
Unable to navigate between vim splits

### ISSUE THREAD

**Issue by amandabeiner** [knubie/vim-kitty-navigator#22]
Hey @knubie, thanks so much for making this plugin, super appreciative of your work! 🙏 

I'm running into an issue similar to the ones mentioned in #2, #8, https://github.com/knubie/vim-kitty-navigator/issues/9#issuecomment-810412643, and #16 but I'm not able to solve it with the suggestions in those threads. Basically, navigating between kitty windows is working great, but I'm not able to navigate between vim splits. 

I've manually set the title in my `.vimrc` and passed a regex as the 4th argument to `pass_keys.py`. Running `:KittyNavigateRight`, etc. manually works great, and it also works if I set the mappings in my `.vimrc` differently than the ones in my kitty.conf.

.vimrc
```vim
set title                                                                        
let&titlestring='%t - vim' 

" Example of setting mappings to something other than what's in kitty.conf, which works
let g:kitty_navigator_no_mappings = 1
nnoremap <silent> <c-a> :KittyNavigateLeft<cr>                                   
nnoremap <silent> <c-s> :KittyNavigateDown<cr>                                   
nnoremap <silent> <c-d> :KittyNavigateUp<cr>                                     
nnoremap <silent> <c-f> :KittyNavigateRight<cr>    
```

kitty.conf
```
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j "^.* - vim$"     
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k "^.* - vim$"     
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h "^.* - vim$"     
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l "^.* - vim$"     
```

I'm on vim 8.2 and kitty 0.23.

I'm very new to kitty and moving over from iterm/tmux/vim-tmux navigator so I was hoping you could let me know if I'm missing something obvious

**Comment by knubie** [comment]
Hi @amandabeiner ,

Could you try adding a print statement in `pass_keys.py` between line 7 and 8 like this:

```python
def is_window_vim(window, vim_id):
    fp = window.child.foreground_processes
    print(fp)
    return any(re.search(vim_id, p['cmdline'][0], re.I) for p in fp)
```

Then run kitty in a debug mode:
```
kitty --debug-keyboard
```
and when the new window is opened, open up vim and some splits and try navigating around. When navigating your vim splits you should see some output similar to this:

```
KeyPress matched action: kitten
[{'pid': 97247, 'cmdline': ['nvim', '.'], 'cwd': '/Users/matt/.config/kitty'}]
```

The `'cmdline': ['nvim', '.']` part will tell us the title of the vim window that we're using to match against in the script. Hopefully that will help debug the situation. Feel free to use this technique to do your own troubleshooting as well.

**Comment by amandabeiner** [comment]
Hi @knubie,

Thanks so much for getting back to me so quickly, and for your kitty debugging tips 😄 They helped me realize that my regex wasn't working as expected. I switched back to the default regex `n?vim` and confirmed that [line 8](https://github.com/knubie/vim-kitty-navigator/blob/17b67e86fe25657473b6d191b1f686ef8f451e8d/pass_keys.py#L8) matches when vim kitty window is focused. Printed output looks like this:

```
KeyPress matched action: kitten
[{'pid': 36353, 'cmdline': ['vim', '/Users/amanda/.config/kitty/pass_keys.py'], 'cwd': '/Users/amanda'}]
```

So now I am able to navigate
- Between vim splits
- From a non-vim kitty window into a vim kitty window
- Around kitty windows

But I am not able to navigate:
- From a vim kitty window to a non-vim kitty window

I've placed breakpoints to confirm that when using a key mapping from a vim window, I'm entering the [`is_window_vim`](https://github.com/knubie/vim-kitty-navigator/blob/17b67e86fe25657473b6d191b1f686ef8f451e8d/pass_keys.py#L31) conditional and the [key mapping is being encoded](https://github.com/knubie/vim-kitty-navigator/blob/17b67e86fe25657473b6d191b1f686ef8f451e8d/pass_keys.py#L32)

I'm going to keep trying on this tomorrow, but if you have any thoughts on where to go next, I'd really appreciate it!

**Comment by knubie** [comment]
Hmm, I think next I would try investigating the [`kitty_navigator.vim`](https://github.com/knubie/vim-kitty-navigator/blob/master/plugin/kitty_navigator.vim) plugin. When you hit the last window, the [`s:KittyAwareNavigate`](https://github.com/knubie/vim-kitty-navigator/blob/master/plugin/kitty_navigator.vim#L41) function should detect that you're at the edge and call [`kitten neighboring_window.py`](https://github.com/knubie/vim-kitty-navigator/blob/master/plugin/kitty_navigator.vim#L56). Could it be that command is not getting executed for some reason?

I think I remember running into this myself a little while ago and it took me forever to figure out, to the point that I thought there was a bug in neovim, but it turned out to be something dumb I did that I forgot about. I can't remember what it was, though.

**Comment by amandabeiner** [comment]
YES you are right it was something silly for me too-- I wasn't setting `allow_remote_control` correctly in my `kitty.conf`. I was using `allow-remote-control` (the command line syntax) instead of `allow_remote_control` (the proper [`kitty.conf`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.allow_remote_control) syntax).

Thanks again for your time, @knubie! Your pointers for where to look next were incredibly helpful 🙏 

For any future readers, the solution was to add the following to my `kitty.conf`:
```
allow_remote_control yes
single_instance yes
listen_on unix:/tmp/mykitty
```
(I'm on MacOS)

I found the error by `echo`-ing the result of `system(cmd)` on line 31 in `kitty_navigator.vim`, and seeing an error that remote control was disabled.
https://github.com/knubie/vim-kitty-navigator/blob/e097580586e802352f225eed467fafa90f11223e/plugin/kitty_navigator.vim#L31

**Comment by knubie** [comment]
Awesome, glad you got it working! Looks like the README might be a bit outdated WRT `kitty.conf`, I'll update that bit and add your `echo system(cmd)` trick to the troubleshooting section.

**Comment by bhushan** [comment]
Hi @amandabeiner and @knubie 

From morning I am trying to setup this, and I have debugged whatever Amanda has mentioned. but for some reason, going out of nvim to kitty panes is not working for me.

```conf
allow_remote_control yes
single_instance yes
listen_on unix:/tmp/mykitty
```

These options are not working for me.
![Screenshot 2022-07-15 at 9 06 19 PM](https://user-images.githubusercontent.com/43483545/179257405-c74801bc-d79e-4b9c-9576-ac217f0e2605.png)


By running `kitty -o allow_remote_control=yes --single-instance --listen-on unix:/tmp/mykitty` this command manually it works, but with those config options its not working for me. I have reloaded config and reopened terminals multiple times to take effect these things.

Screenshot has both nvim and kitty versions, and I am on Mac M1.

**Comment by bhushan** [comment]
Actually i solved it with above settings.. catch was to completely close kitty and then re run.. then only remote control configuration takes effect.. also there is no setting for single instance.. so removing that .. doesnt errors out when we reload configuration.. after debugging these stuffs.. I figured it out.. thanx for help..

**Comment by bhushan** [comment]
https://github.com/knubie/vim-kitty-navigator/pull/34 this PR makes it clear for future users..
