### ISSUE TITLE
Failed to launch child: @ With error: No such file or directory

### ISSUE THREAD

**Issue by ghostbuster91** [knubie/vim-kitty-navigator#27]
Hi, I am trying to get this working with kitty via nix and I've just run into following error:

```
Failed to launch child: @
With error: No such file or directory
Press Enter to exit.
```
It happens each time I try to move out from the vim window to kitty window. It works when switching between vim panels, and between kitty windows and when entering vim window from kitty.

Version:
`kitty 0.23.1`
`kitty-vim-navigator commit hash 443287463671020b461cec020ced52840723b95d`

kitty launch parameters:
```
kitty -o allow_remote_control=yes --single-instance --listen-on unix:@mykitty
```

Any idea what could be wrong or how can I debug that further?

**Comment by knubie** [comment]
When you go from vim to kitty, vim calls a command like:
```
kitty @ kitten neighboring_window.py right
```

See [this line](https://github.com/knubie/vim-kitty-navigator/blob/master/plugin/kitty_navigator.vim#L57) in the plugin for how that gets called from within vim. Can you try running `kitty @ kitten neighboring_window.py right` from the command line with a couple of split windows to make sure that works?

**Comment by ghostbuster91** [comment]
Calling this line explicitly causes mentioned error. However calling that kitten from kitty-shell works :thinking: 
![Peek 2022-01-08 11-30](https://user-images.githubusercontent.com/5662622/148640973-ab049763-a1fd-4f0c-a539-0b41a838a65e.gif)

**Comment by knubie** [comment]
Are you able to use any remote control commands using `kitty @ ...`? Or run any other kittens via remote control? `kitty @ kitten...` If not then maybe it would be worthwhile to open an issue on the kitty github repo, or reach out for help on the IRC channel (if there is one). I'm afraid helping to troubleshoot this issue is probably outside my abilities.

**Comment by ghostbuster91** [comment]
You are right, I am not able to call these commands outside from `kitty`. I will do as suggested and reach out to kitty maintainers. Anyway, thanks for help! :)
