### ISSUE TITLE
Kitty 0.24.1 not working

### ISSUE THREAD

**Issue by dahmc** [knubie/vim-kitty-navigator#28]
It's not working for me on latest Kitty, but I see no error messages.

And I'm quite confused: https://github.com/knubie/vim-kitty-navigator/issues/25 referenced a PR that was opened, but then not merged and just closed?

What do I have to change to make it work?

**Comment by knubie** [comment]
AFAIU that PR was closed because the fix was already in master, but the author just hadn't updated yet.

Are you on the latest commit? Have you tried the [troubleshooting steps](https://github.com/knubie/vim-kitty-navigator#troubleshooting)?

**Comment by dahmc** [comment]
Thanks for getting back to me. I apologize, it was a mess up on my end. It turned out my launcher still started the previous version of kitty.
