### ISSUE TITLE
Delay when transitioning from vim to shell window

### ISSUE THREAD

**Issue by strogonoff** [knubie/vim-kitty-navigator#3]
Issue in action:

![vim-kitty-navigator-delay](https://user-images.githubusercontent.com/292959/67128099-4bc28480-f22d-11e9-8f64-ac14ccfdf59d.gif)

Note some time between cursor vanishing in vim and appearing in the next window. Doesn’t happen between two shell windows, only when switching from vim to another window.

Since it’s not instantaneous, there’s a chance of sending keystrokes intended for shell to Vim instead. Not a huge issue, only somewhat disrupts flow.

I suppose it has to do with Python and/or remote kitty calls.

Could be specific to my system, though. Didn’t test on others.

**Comment by knubie** [comment]
@strogonoff I don't think it's specific to your system as I experience the delay too. I looked into it awhile ago but wasn't able to come up with a fix. Happy to take a PR though if you can figure out what's going on.

**Comment by strogonoff** [comment]
I tried timing how long it takes for [this command](https://github.com/knubie/vim-kitty-navigator/blob/master/plugin/kitty_navigator.vim#L34) to complete by adding `time` command in front of it. It reports 0.05s.

However, if I add a debug print before and after the `call s:KittyCommand(args)` line, perceptually it takes about half a second between the prints appearing in vim prompt.

So I may be mistaken, but it seems like most of the time is in vim calling the kitty command, not within kitty command itself. I couldn’t find any way to speed that up.

**Comment by strogonoff** [comment]
Vim’s profiling reports:

```
FUNCTION  <SNR>21_KittyCommand()
    Defined: ~/dotfiles2/vim/.vim/bundle/vim-kitty-navigator/plugin/kitty_navigator.vim:33
Called 2 times
Total time:   1.116267
 Self time:   0.000360

count  total (s)   self (s)
                              " let cmd = 'kitty @ --to ' . g:kitty_navigator_listening_on_address . ' ' . a:args
    2              0.000016   let cmd = 'time kitty @ --to ' . g:kitty_navigator_listening_on_address . ' ' . a:args . ' > /Users/tonys/vkn-profile.txt 2>&1'
    2   1.116243   0.000336   return system(cmd)

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    2   1.116267   0.000360  <SNR>21_KittyCommand()
```

**Comment by strogonoff** [comment]
From [this answer](https://vi.stackexchange.com/a/6712) I gather that it could be improved by making calls via Python instead of vimscript, but that would require Vim to be compiled with native Python support

**Comment by knubie** [comment]
Thanks a lot for looking into this @strogonoff .

I copied most of the code in this repo from [christoomey/vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator), and I don't remember there being such a delay in their plugin.

Here's the relevant snippet:
https://github.com/christoomey/vim-tmux-navigator/blob/master/plugin/tmux_navigator.vim#L63

I don't have tmux anymore, but it might worth checking out that plugin and see if there's also a delay when switching to a tmux pane from vim.

**Comment by strogonoff** [comment]
I just checked and the delay is perceptually the same with `vim-tmux-navigator`. I don’t remember it, perhaps there’s a change in latest Homebrew vim (`8.1 (2018 May 18, compiled Oct 15 2019 10:20:59)`) and/or macOS 10.15.

**Comment by pyrho** [comment]
First of all thank you for this great plugin, it's a very useful addition to my workflow !

I too am bothered by the noticeable delay occurring when switching from Vim to a Kitty window.
I don't think the issue is with they way you are calling the Kitty from vimscript, the same delay is noticeable when calling `kitty @ kitten neighboring_window.py left` manually.

So the issue is with Kitty itself, probably due to the fact that it is executing a python script, writing to a unix socket, on which kitty listen, parse and execute the command.

**Comment by knubie** [comment]
Seems like an upstream issue.
