### ISSUE TITLE
Cannot move from nvim back to kitty

### ISSUE THREAD

**Issue by traviscrist** [knubie/vim-kitty-navigator#43]
I followed the setup instructions with:
- kitty 0.28.1
- nvim 0.9.0

I can easily: 
- Go from kitty -> nvim
- Go from kitty -> another kitty window

I cannot: 
- Go from nvim -> kitty

I enabled the debug and I see this output: 
```
---------------- key down -------------------
NSEvent: type=KeyDown loc=(403.758,708.441) time=714380.7 flags=0x40101 win=0x106657470 winNum=25039 ctxt=0x0 chars="
" unmodchars="j" repeat=0 keyCode=38
Press: native_key: 0x26 (j) glfw_key: 0x6a mods: ctrl char_count: 1 deadKeyState: 0 repeat: 0
	TextInputCtx: doCommandBySelector: (noop:)
text: <none> glfw_key: j marked_text: ()
on_key_input: glfw key: 0x6a native_code: 0x26 action: PRESS mods: ctrl text: '' state: 0
KeyPress matched action: kitten
[{'pid': 92320, 'cmdline': ['nvim', 'README.md'], 'cwd': '/Users/travis'}]
handled as shortcut
```

It seems like that all is correct. Is there another next step I can take to debug why this is not working? 

Thanks!

**Comment by rrpolanco** [comment]
Experiencing a similar issue except that I can't go from nvim to nvim window.

**Comment by skdillon** [comment]
Also having this issue

**Comment by skdillon** [comment]
I get this error when `KittyCommand` runs this line: `return system(cmd)`

```
Executing command: kitty @ --password="0" kitten neighboring_window.py bottom                                                                          
Output from KittyCommand: Error: open /dev/tty: device not configured      
```

**Comment by skdillon** [comment]
Found a temporary solution.

I edited `kitty_navigator.vim`

and changed 

to

```
function! s:KittyCommand(args)
  let pw = get(g:, 'kitty_navigator_password', 0)
  let pw_s = pw != "" ? '--password="' . pw . '" ' : ''
  let cmd = 'kitty @ --to=$KITTY_LISTEN_ON ' . pw_s . a:args
  return system(cmd)
endfunction
```

Note the addition of `--to=$KITTY_LISTEN_ON '`

in my kitty confg I added:

```
allow_remote_control yes
listen_on unix:/tmp/mykitty
```

**Comment by traviscrist** [comment]
@knubie can we reopen this, I have both those settings that @skdillon set already and the issue is still present. I had them setup correctly from beginning when filing the issue. 

@rrpolanco are you still having this issue as well?

**Comment by traviscrist** [comment]
Oh maybe this is effectively replaced by https://github.com/knubie/vim-kitty-navigator/issues/41 following it now.

**Comment by critterjohnson** [comment]
@knubie I am having this issue with latest `nvim` (0.8.3), latest `vim-kitty-runner`. Works fine in `vim`. I was planning on switching to `nvim` but I have become so completely reliant on this plugin that I cannot until this works.

Relevant lines in `~/.config/kitty/kitty.conf`
```
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+l kitten pass_keys.py right  ctrl+l
allow_remote_control yes
listen_on unix:/tmp/mykitty
```

Relevant lines in `~/.config/nvim/init.lua`
```lua
if os.getenv("TERM") == "xterm-kitty" then
    vim.g.kitty_navigator_no_mappings = 1

    vim.api.nvim_set_keymap('n', 'C-h', ':KittyNavigateLeft <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-j', ':KittyNavigateDown <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-k', ':KittyNavigateUp <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-l', ':KittyNavigateRight <CR>', { noremap = true, silent = true })
end
```

Manually running `:KittyNavigateLeft` does not work, and I am confident the mappings are good.

**Comment by knubie** [comment]
@traviscrist Are you able to navigate within vim? In your OP you said you couldn't go from vim to kitty, but are you able to go from one vim pane to another?

**Comment by traviscrist** [comment]
> @traviscrist Are you able to navigate within vim? In your OP you said you couldn't go from vim to kitty, but are you able to go from one vim pane to another?

@knubie I can easily move from Kitty -> Nvim and then within Nvim I have no issues moving between panes, I just cannot get the jump back to Kitty to work unfortunately.

**Comment by critterjohnson** [comment]
> > @traviscrist Are you able to navigate within vim? In your OP you said you couldn't go from vim to kitty, but are you able to go from one vim pane to another?
> 
> @knubie I can easily move from Kitty -> Nvim and then within Nvim I have no issues moving between panes, I just cannot get the jump back to Kitty to work unfortunately.

I had this issue yesterday and figured it out eventually. Here were my debugging steps:
1. ran `kitty --version` (`kitty 0.32.0 created by Kovid Goyal`)
2. started `kitty` from the command line with
  ```
  kitty -o allow_remote_control=yes --single-instance --listen-on unix:/tmp/mykitty # this is the command for MacOS
  ```
3. after that worked with newest kitty, I realized that the `kitty` in my `/Applications` folder and the one installed elsewhere had become out of sync (how I do not know, likely through some MacOS BS)
4. removed `kitty` from my `/Applications` folder and reinstalled

**Comment by traviscrist** [comment]
@critterjohnson thanks for the tip, I upgraded to kitty 0.32.0 and checked whats in my applications folder and they are the same. Running that cmd to start kitty from the cmd line does not work for me. I get the same behavior, I can move to nvim but I cannot leave back to kitty.

**Comment by critterjohnson** [comment]
> @critterjohnson thanks for the tip, I upgraded to kitty 0.32.0 and checked whats in my applications folder and they are the same. Running that cmd to start kitty from the cmd line does not work for me. I get the same behavior, I can move to nvim but I cannot leave back to kitty.

Maybe worth upgrading to nvim 0.9.5? That's the only major difference in our env as far as I can tell. Also worth triple-checking that you're using the most up-to-date scripts from this repo.

Also make sure your `nvim` bindings are correct. These are the relevant lines in my `~/.config/nvim/init.lua`:

```
-- vim-lazy - plugins
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    { "knubie/vim-kitty-navigator" },
})

-- vim-kitty-navigator
if os.getenv("TERM") == "xterm-kitty" then
    vim.g.kitty_navigator_no_mappings = 1
    vim.g.tmux_navigator_no_mappings = 1

    vim.api.nvim_set_keymap('n', 'C-h', ':KittyNavigateLeft <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-j', ':KittyNavigateDown <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-k', ':KittyNavigateUp <CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', 'C-l', ':KittyNavigateRight <CR>', { noremap = true, silent = true })
end
```

The fact that you can navigate between kitty windows and within `nvim` but not between the two smells to me like 1. your keybinds are being eaten by another plugin or 2. your `vim-kitty-navigator` version is out of sync with `nvim` / `kitty`. If you're running MacOS and you're confident your versions are correct I would suggest temporarily moving your `init.lua` or `init.vim` temporarily and trying that `init.lua`.

**Comment by traviscrist** [comment]
@critterjohnson wow, thanks that actually worked, I always I assumed from the directions that I did not need to add the key mappings. 

I had:
```
-- Window Splitting
-- map('n', '<C-J>', '<C-W><C-J>', default_options)
-- map('n', '<C-K>', '<C-W><C-K>', default_options)
-- map('n', '<C-L>', '<C-W><C-L>', default_options)
-- map('n', '<C-H>', '<C-W><C-H>', default_options)
```

Changing these to:
```
-- Kitty Navigate Splits
map('n', '<C-J>', ':KittyNavigateDown <CR>', default_options)
map('n', '<C-K>', ':KittyNavigateUp <CR>', default_options)
map('n', '<C-L>', ':KittyNavigateRight <CR>', default_options)
map('n', '<C-H>', ':KittyNavigateLeft <CR>', default_options)
```

Seems to have worked, and it still seems to be working perfectly. Thanks for the tips! ❤️

**Comment by knubie** [comment]
You shouldn't need to manually add the default keybindings to your vim config because the plugin already does that.

https://github.com/knubie/vim-kitty-navigator/blob/20abf8613aa228a5def1ae02cd9da0f2d210352a/plugin/kitty_navigator.vim#L17-L22

But I think if you do add keybindings it will override the ones set in the plugin, which seems to be what was happening here.

**Comment by critterjohnson** [comment]
@knubie FWIW, I had the exact same issue back when I was installing this a long time ago. Manually setting them fixed it for me.
