### ISSUE TITLE
navigate to next and previous window istead to neighboring windows

### ISSUE THREAD

**Issue by gitacrobat** [knubie/vim-kitty-navigator#46]
Right now `<ctrl-j> `and `<ctrl-k>` use kitty's _neighboring_window_ commands. I would like instead to map `<ctrl-j>` and `<ctrl-k>` to kitty's _next_window_ / _prev_window_ commands.

Is this possible?

**Comment by knubie** [comment]
Should be possible, but not without editing the source code of the plugin.

https://github.com/knubie/vim-kitty-navigator/blob/c3d8aaaa61717b2c142ff39553fcab709fd606a7/pass_keys.py#L46
