### ISSUE TITLE
Do you consider supporting neovim?

### ISSUE THREAD

**Issue by ShelpAm** [knubie/vim-kitty-navigator#50]

**Comment by hubcio2115** [comment]
Neovim supports Vim plugins out of the box. For a lua configuration you can reference [this](https://github.com/knubie/vim-kitty-navigator/issues/5#issuecomment-1460314405)

**Comment by ShelpAm** [comment]
> Neovim supports Vim plugins out of the box. For a lua configuration you can reference [this](https://github.com/knubie/vim-kitty-navigator/issues/5#issuecomment-1460314405)

Thank you! That helps a lot.
