### ISSUE TITLE
Neovim windows are skipped

### ISSUE THREAD

**Issue by ngmoviedo** [knubie/vim-kitty-navigator#8]
I have configured both Neovim and Kitty following the documentation. The expected result would that ctrl+h/j/k/l allowed to seamlessly  change between neovim and kitty splits. Sadly I am only able to change between kitty splits. The `:KittyNavigateDown`, etc command do actually work when executed manually or when they are mapped to different keys, but not when the same keys are used for both kitty and neovim.
If the window title is changed, as it's mentioned in the documentation, I get the opposite result. Can alternate between neovim windows, but not kitty ones.
It seems to be a similar issue to the one described by some users in #2.

**Comment by knubie** [comment]
@ngmoviedo I just pushed a new version, re-download and give it a try and let me know if it works.

**Comment by ngmoviedo** [comment]
Like a charm! Except with netrw windows (can't go from them to a terminal window directly), but that may be a different issue, and I guess much more difficult to solve.
Thanks for this useful plugin and the support. That was fast!

**Comment by knubie** [comment]
Glad it's working :-) Netrw might not be working because it has its [own bindings for `<c-l>` and `<c-h>`](https://gist.github.com/danidiaz/37a69305e2ed3319bfff9631175c5d0f)? I hadn't noticed since I used nerdtree, but i tried it and I could go to the left (`<c-h>`) but not the right (`<c-l>`).

**Comment by pgrond** [comment]
Sorry to bump a closed issue, but I have the same issue. Manualy executing the commands works, but keybindings not. I'm on the latest version of kitt-navigator and on nvim nightly v0.5.0-dev+1023-gea8756f85
