### ISSUE TITLE
Can't get it working, errors in console

### ISSUE THREAD

**Issue by osenvosem** [knubie/vim-kitty-navigator#9]
MacOS 11.1, Kitty 0.19.3

```
Traceback (most recent call last):
  File "kitty/boss.py", line 661, in dispatch_special_key
  File "kitty/boss.py", line 723, in dispatch_action
  File "kitty/boss.py", line 944, in kitten
  File "kitty/boss.py", line 885, in _run_kitten
  File "/Users/serg/.config/kitty/pass_keys.py", line 32, in handle_result
    w = boss.indow_id_map.get(target_window_id)
AttributeError: 'Boss' object has no attribute 'indow_id_map'
```

**Comment by knubie** [comment]
Looks like `window_id_map` is misspelled in `pass_keys.py`? Did you modify the file?

**Comment by osenvosem** [comment]
@knubie yep, you are right it was misspelled. Not sure how it happened.
Either way, now it switches between kitty windows and doesn't work in vim splits.

**Comment by NikoKS** [comment]
This might help as it's what makes it work for me:
1. on neovim, set the title with :set title
2. on kitty.conf set allow_remote_control to socket-only and listen_on to unix:/tmp/mykitty
hope it helps

**Comment by osenvosem** [comment]
@NikoKS thanx, but this didn't help, switching vim splits still don't work.

**Comment by knubie** [comment]
@osenvosem Have you tried with a completely empty vim config (other than the vim-kitty-navigator settings)? If it works with an empty config file, that might help narrow down the problem.

**Comment by NikoKS** [comment]
oh and one last thing I did was changing the kitty.conf mapping regex to:
"^.* - NVIM$"
since that's the default title format given by neovim

**Comment by osenvosem** [comment]
Trying it again and having an error. Installed according to instruction.

```
❯ kitty -o allow_remote_control=yes --single-instance --listen-on unix:@mykitty
[089 12:18:08.147434] Traceback (most recent call last):
  File "kitty/main.py", line 344, in main
  File "kitty/main.py", line 337, in _main
  File "kitty/main.py", line 160, in __call__
  File "kitty/main.py", line 138, in _run_app
  File "kitty/boss.py", line 159, in __init__
  File "kitty/boss.py", line 73, in listen_on
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by knubie** [comment]
@osenvosem I think `@mykitty` only works with linux. I'll update the readme.

**Comment by osenvosem** [comment]
@knubie OK, it helped to start kitty. But switching Vim splits still doesn't work, even with completely empty vim configuration (other than the vim-kitty-navigator). As you can see on the video Vim split in the middle is ignored.

https://user-images.githubusercontent.com/6762673/113024843-e4ce2c80-918f-11eb-9748-294df52633e9.mov

**Comment by atidyshirt** [comment]
I am having the same issue on Mac, it ignores vim splits

**Comment by critterjohnson** [comment]
@atidyshirt can you document the fix here?

**Comment by atidyshirt** [comment]
I am not currently using this, but I think I had the following setup.

Vimrc

```
set title
let &titlestring='%t - Vim'

" not sure if you need to rebind this locally, think kitty does this for you
imap <C-h> <C-w>h
imap <C-j> <C-w>j
imap <C-k> <C-w>k
imap <C-l> <C-w>l
```

Kitty.conf

```
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j "^.* - Vvim$"
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k "^.* - Vim$"
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h "^.* - Vim$"
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l "^.* - Vim$"
```

Bind to open kitty:

`cmd - return : /Applications/Kitty.app/Contents/MacOS/kitty -o allow_remote_control=yes --listen-on unix:@mykitty --single-instance -d ~ &> /dev/null`

> NOTE: you might need to play around with --listen-on unix:@mykitty it could also be --listen-on unix:/tmp/mykitty
> I just cant remember.

Anyway hope this helps :)

**Comment by critterjohnson** [comment]
Thanks!

**Comment by Nudin** [comment]
I also had troubles getting it working and wasted a lot of time debugging, and at the end it was a trivial thing: Due to starting kitty with `--single-instance` you need to make sure to quit all kitty windows after installing or changing any setting. Maybe this should be added to the install section?
